### ISSUE TITLE
Error in codecs while printing article content

### ISSUE THREAD

**Issue by Griffintaur** [Griffintaur/News-At-Command-Line#1]
There is some issue while printing output using different codecs.

**Comment by vsingh0075** [comment]
Hi, I am totally a beginner here. I have read the code and I want to help. Can you please elaborate what codecs you are talking about ?

**Comment by Griffintaur** [comment]
The codec is basically an encoding used to represent characters.You might have heard of ASCII, UTF-8. These are the types of the encoding.You might receive some SMS in different languages on your phones and your phones might not be able to handle those languages, then what should be done in that case?

The problem is if we receive some text from websites requests where different encoding is used and now if we want to output the same text on the screen where different encoding is used, then there may be some inconsistency between the two different methods of encoding.
 what we want to do here.
1. either check the encoding the output part and enforce the text before flushing to output to be in the same encoding and replace the characters where there is no matching with some predetermined characters?
2.make the output to be in sync with encoding used for the text.

**Comment by vsingh0075** [comment]
Yeah, we should keep a standard encoding.
I think we can use pyicu module to check the encoding of data fetched from News server and convert all the data to only say, UTF-8.

**Comment by Griffintaur** [comment]
Go ahead and try that out and submit a pull request if things go as per your plan.
Contact me for any help if needed....
Best wishes from my side

**Comment by agiridharan** [comment]
Hi if this issue still open? I would like to help if it is

**Comment by Griffintaur** [comment]
Yes, it is open. and if u want more description about the issue, you should check my comments in this thread

**Comment by HungryAdi** [comment]
Hey! Is this issue still open? I'd like to help!

**Comment by Griffintaur** [comment]
@HungryAdi  yes, it's still open. You can go for it

**Comment by kalbhor** [comment]
Hey, has this issue been resolved? If not, I'd like to help.

**Comment by wflores96** [comment]
Not sure if this has been addressed yet and also not super familiar with encoding or requests, but I took a crack at it and submitted a PR #17
