### ISSUE TITLE
Make code pep8 compliant

### ISSUE THREAD

**Issue by sachet-mittal** [Griffintaur/News-At-Command-Line#18]

**Comment by sachet-mittal** [comment]
I would like to take this up.

**Comment by sachet-mittal** [comment]
Pull request for this is:
https://github.com/Griffintaur/News-At-Command-Line/pull/19

**Comment by pulkitmaloo** [comment]
I would like to take this up if it hasn't been completed yet.

**Comment by ShashwatNigam99** [comment]
Has this issue been resolved ?
