### ISSUE TITLE
Saving the Article to the File

### ISSUE THREAD

**Issue by Griffintaur** [Griffintaur/News-At-Command-Line#6]
Currently, we can just view the article from different news sources,
what we want is to extend the functionality to save the article into some file type
which can be viewed by the user later on?

Requirements:
1. Save Function for the Article
2. Asking a user to save or not.
3. Setting some Default Folder path in the config file where Files will be saved

**Comment by yblank1** [comment]
What do you mean by default database?

**Comment by Griffintaur** [comment]
What I meant was "Default Folder". I  have edited the comment now. Thanks @yblank1
